### PR TITLE
[frontend] add new benefit navigator page

### PR DESCRIPTION
**Pull request by Fbasham**
# [add article 1 for Benefit navigator page](https://dev.azure.com/VP-BD/DECD/_boards/board/t/Service%20Canada%20Labs/Stories%20and%20Activities/?workitem=130039)

## Description
- add dynamic page
- add to re-writes

### CODE REVIEW

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://alphasite-appservice-dev-0.azurewebsites.net

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://alphasite-appservice-dev-0.azurewebsites.net

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://alphasite-appservice-dev-0.azurewebsites.net

**Comment by will0684** [comment]
Okay @Fbasham I reverted most of the dependency versions to v1.9.1 but tried to keep updates to the i18n dependencies up to the point that they aren't causing errors with language toggle or navigation to the article pages. It seems to also still support your updates to the error pages in a working fashion so thats very good. Please test with fresh node_modules and yarn install and let me know if you see any issues!

**Comment by Fbasham** [comment]
> Okay @Fbasham I reverted most of the dependency versions to those at v1.9.1 but tried to keep updates to the i18n dependencies up to the point that they aren't causing errors with language toggle or navigation to the article pages. It seems to also still support your updates to the error pages in a working fashion so thats very good. Please test with fresh node_modules and yarn install and let me know if you see any issues!

working as expected

**Review by will0684 — APPROVED** [review]
Nice work thank you!

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://alphasite-appservice-dev-0.azurewebsites.net

**Pull request merged**
