### PR TITLE
Storybook Entries

### PR DESCRIPTION
**Pull request by blai0264**
# [[Storybook Entries](https://dev.azure.com/VP-BD/DECD/_boards/board/t/Service%20Canada%20Labs/Stories%20and%20Activities?workitem=162910)]

- Upgraded to Storybook 8
- Added storybook entries for Fragment Renderer Components
- Updated next/image imports
- Implemented next/jest and removed babel-jest

## Test Instructions
1. yarn storybook
2. Navigate through the Storybook entries for fragment renderer and confirm they are working properly.

### CODE REVIEW

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://app-servicecanadalabs-dev-pr-preview-2.azurewebsites.net

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://app-servicecanadalabs-dev-pr-preview-2.azurewebsites.net

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://app-servicecanadalabs-dev-pr-preview-2.azurewebsites.net

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://app-servicecanadalabs-dev-pr-preview-2.azurewebsites.net

**Review by will0684 — APPROVED** [review]
Looks good nice work! 🚀

**Pull request merged**
