### PR TITLE
[frontend] add recursive gql-node-renderer

### PR DESCRIPTION
**Pull request by Fbasham**
# [Implement support for Benefits Navigator update/blog pages](https://dev.azure.com/VP-BD/DECD/_boards/board/t/Service%20Canada%20Labs/Stories%20and%20Activities/?workitem=132754)

### Description

This code is intended to remove the need for hard-coding the HTTP response data returned from our GraphQL data fetching.  More specifically, this code introduces a recursive react component that accepts the JSON data as props, and reconstructs the DOM from that data.

### CODE REVIEW

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://alphasite-appservice-dev-pr-preview-0.azurewebsites.net

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://alphasite-appservice-dev-pr-preview-0.azurewebsites.net

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://alphasite-appservice-dev-pr-preview-0.azurewebsites.net

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://alphasite-appservice-dev-pr-preview-0.azurewebsites.net

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://alphasite-appservice-dev-pr-preview-0.azurewebsites.net

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://alphasite-appservice-dev-pr-preview-0.azurewebsites.net

**Review by will0684 — APPROVED** [review]
Great work thank you!

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://alphasite-appservice-dev-pr-preview-0.azurewebsites.net

**Pull request merged**
