### PR TITLE
Consolidate Design System Components

### PR DESCRIPTION
**Pull request by will0684**
# [Modify component directory structure](https://dev.azure.com/VP-BD/DECD/_boards/board/t/Service%20Canada%20Labs/Stories%20and%20Activities)

This PR includes:

- Consolidation of our imported design-system components into our pre-existing component structure
- Added Stories and unit tests for imported design-system components
- Added jsconfig.json to support checking file references in VSCode

## Test Instructions

1. `yarn storybook`
2. See that DSButton, Image, Link, Collapse, CTA, Heading and Footer render without errors in the viewer
3. `yarn build` & `yarn start`
4. See that app builds and runs without errors

### CODE REVIEW

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://app-servicecanadalabs-dev-pr-preview-1.azurewebsites.net

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://app-servicecanadalabs-dev-pr-preview-1.azurewebsites.net

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://app-servicecanadalabs-dev-pr-preview-1.azurewebsites.net

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://app-servicecanadalabs-dev-pr-preview-1.azurewebsites.net

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://app-servicecanadalabs-dev-pr-preview-1.azurewebsites.net

**Review by MarcoGoC — APPROVED** [review]
Looks good minor details that might be as requested idk

**Pull request merged**
