### PR TITLE
Splash page styling

### PR DESCRIPTION
**Pull request by shawn320**
# Description

The purpose of this pr is to update the styling for the splash page. In my previous pr, there are some styling issues for the background image and the main cta card. The main issue was the background image being cut off when the screen resolution gets bigger, this should be fixed in this pr. 

I also updated the styling for the main cta to match the new design on Figma. Updated the background to use a slightly darker color instead of pure white, and applied box shadow. 

## Acceptance Criteria

Splash page matches the new design on [Figma](https://www.figma.com/file/ke3SrZNGMP3AjwzMMuEgbo/%5Bcurrent%5D-BDM-DECD-SC-Labs?node-id=10436%3A27681)

## Test Instructions

1. yarn dev
2. visit the splash page (make sure to clear cookies, otherwise you'll be redirected to the home page)
3. check the styling

## Checklist

- [ ] Strings use placeholders for translation (No hard coded strings)
- [ ] Unit tests have been added/updated
- [ ] Update CHANGELOG

### CODE REVIEW

**Review by krischarbonneau — COMMENTED** [review]
At 320px screen width the image gets very squished towards the bottom of the screen. 
Can we juxtapose the cta over the image/have the image more centered like the Figma designs?

**Review by krischarbonneau — COMMENTED** [review]
This looks a lot better now, once my previous comment has been taken care of I'll go ahead and approve this. Great job!

**Comment by shawn320** [comment]
> This looks a lot better now, once my previous comment has been taken care of I'll go ahead and approve this. Great job!

**Review by krischarbonneau — APPROVED** [review]
Great work!

**Pull request merged**
