### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by andr0272**
# Pipeline documentation

Added some documentation for the pipelines. Also creating a copy of the pipelines under one folder. Will point ADO to these new pipeline files, then delete the old ones from the root of the repo (Cleaning up!)
## Test Instructions

1. Read the docs
2. Proofread the docs

### CODE REVIEW

**Comment by andr0272** [comment]
A pull request preview is being generated. Hold tight!

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://alphasite-appservice-dev-pr-preview-1398768870.azurewebsites.net

**Review by will0684 — DISMISSED** [review]
Super thorough and straightforward to understand. Great work and thank you for going through this!

**Comment by andr0272** [comment]
A pull request preview is being generated. Hold tight!

**Review by will0684 — APPROVED** [review]
Thank you!

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://alphasite-appservice-dev-pr-preview-1398768870.azurewebsites.net

**Pull request merged**
