### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by andr0272**
# General Cleanup (Tech debt related)

General cleanup of the following areas:
- Deprecated pages and APIs
- Environment variables (Either duplicates or unused)
- Dockerfile repeated instructions

## Test Instructions

1. Reinstall dependencies (`yarn`)
2. Run a development build `yarn run dev` and navigate to each page of the app, verifying there are no crashes.
3. Try the new docker command in packagelock.json `yarn run docker:build`. Once the build has completed, run the container with `yarn run docker:run` and verify you can navigate to the app via browser. 

## Definition of Done

- [ ] Update CHANGELOG

### CODE REVIEW

**Review by Fbasham — COMMENTED** [review]
So I've checked this out, built the image locally and ran it.  It appears to work well enough.  I'm getting a lot of warnings/errors in the terminal however, related to some of our data fetching from the graphql endpoint.  Unsure if it's related to this PR, or not, so I'm going to have to dig a bit deeper before approving.

Here's some of the terminal output:

`TypeError: Cannot read properties of undefined (reading 'scLabsPagev1ByPath')
    at getStaticProps (/app/.next/server/pages/home.js:288:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.renderToHTML (/app/node_modules/next/dist/server/render.js:386:20)
    at async doRender (/app/node_modules/next/dist/server/base-server.js:809:34)
    at async cacheEntry1.responseCache.get.incrementalCache.incrementalCache (/app/node_modules/next/dist/server/base-server.js:929:28)
    at async /app/node_modules/next/dist/server/response-cache/index.js:83:36`

**Review by Fbasham — APPROVED** [review]
Okay, so the errors/warning I mentioned yesterday are also present if using the previous image, and really I don't believe it's worrisome either.  It's just terminal pollution because of failed fetch requests using the AEMService.  Everything still works though. 

We'll need to cleanup the tests since pages have been removed, but this can done in a separate PR and added to the board.

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://alphasite-appservice-dev-0.azurewebsites.net

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://alphasite-appservice-dev-0.azurewebsites.net

**Comment by will0684** [comment]
We need to clean up the tests that correspond with the removed pages because they will fail in the pipeline

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://alphasite-appservice-dev-3.azurewebsites.net

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://alphasite-appservice-dev-3.azurewebsites.net

**Review by will0684 — DISMISSED** [review]
Tested and appears to be working as expected. Thank you for your work on this!

**Comment by andr0272** [comment]
> image
> 
> I love seein' it.

It's not a rewrite :upside_down_face:

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://alphasite-appservice-dev-pr-preview-3.azurewebsites.net

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://alphasite-appservice-dev-pr-preview-3.azurewebsites.net

**Review by will0684 — APPROVED** [review]
Thank you 👍

**Pull request merged**
