### PR TITLE
Image vertical line content update

### PR DESCRIPTION
**Pull request by blai0264**
# [Modify ImageVerticalLineContent component to support new layout](https://dev.azure.com/VP-BD/DECD/_boards/board/t/Service%20Canada%20Labs/Stories%20and%20Activities?workitem=220633)

1. Updated ImageVerticalLine Content component to include optional collapse
2. Updated components affected by this change
3. Updated storybook entries for components affected by this change)
4. Updated unit tests for components affected by this change
5. Got unit tests for collapse components successfully testing that the collapse is opened after being clicked.

## Test Instructions

1. yarn test:unit
2. verify all tests are successful
3. yarn storybook
4. verify each component with collapse is rendered properly
5. yarn build
6. yarn start

### CODE REVIEW

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://app-servicecanadalabs-dev-pr-preview-1.azurewebsites.net

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://app-servicecanadalabs-dev-pr-preview-1.azurewebsites.net

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://app-servicecanadalabs-dev-pr-preview-1.azurewebsites.net

**Review by will0684 — APPROVED** [review]
Nice work thank you

**Pull request merged**
