### PR TITLE
Benefits Finder project page

### PR DESCRIPTION
**Pull request by will0684**
# [Benefits Finder project page](https://dev.azure.com/VP-BD/DECD/_boards/board/t/Service%20Canada%20Labs/Stories%20and%20Activities?workitem=208658)

Added Benefits Finder project page and some basic unit and e2e tests.

## Test Instructions

1. See that Benefits Finder card appears on homepage, toggle language
2. Navigate to project page using card, toggle language

### CODE REVIEW

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://app-servicecanadalabs-dev-pr-preview-0.azurewebsites.net

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://app-servicecanadalabs-dev-pr-preview-0.azurewebsites.net

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://app-servicecanadalabs-dev-pr-preview-0.azurewebsites.net

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://app-servicecanadalabs-dev-pr-preview-0.azurewebsites.net

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://app-servicecanadalabs-dev-pr-preview-0.azurewebsites.net

**Review by blai0264 — APPROVED** [review]
great work dude!

**Pull request merged**
